server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.255.101:8848
    gateway:
      routes:
          - id: pay-service
            uri: lb://pay-service
            predicates:
              - Path=/pay-orders/**

          - id: item-service
            uri: lb://item-service
            predicates:
              - Path=/items/**,/search/**

          - id: trade-service
            uri: lb://trade-service
            predicates:
              - Path=/orders/**

          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/users/**,/address/**


          - id: cart-service
            uri: lb://cart-service
            predicates:
              - Path=/carts/**


